### ISSUE TITLE
question: Was there any particular reason to go with GPL over MIT

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#11]
Was there any particular reason to go with GPL over MIT which larval uses and do you have plans to go MIT?

Thanks

**Comment by chadanuk** [comment]
Hi,

Thanks for your interest and the query. We weren't initially sure what the best options was. Part of the reason for choosing GPL was to emulate other CMS projects such as Wordpress/Drupal and also the direct integration within Github. 

We aren't averse to changing the license, however, should it be a major issue.
