### ISSUE TITLE
external routes

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#12]
Hi, I'm trying to load a separate routes file.

I've tried loading them from my own provider.

```
        $routeFile = base_path('/Modules/Test/Routes/web.php');
        event(new LoadRouteFile($routeFile));
        if ($routeFile && file_exists($routeFile)) {
            include $routeFile;
        }
```

and

```
if (\CoasterCms\Helpers\Cms\Install::isComplete()) {

    include __DIR__ . '/routes/admin.php';
    include __DIR__ . '/routes/cms.php';

    include base_path('/Modules/Test/Routes/web.php');

} else {
```

I know the routes are there because artisan route:list is showing them.

Every time I try to hit my page I get redirected back to the admin area. (I'm exploring and testing through the admin area).

if I comment out

```
// Route::any($adminUrl . '{other}', 'CoasterCms\Http\Controllers\AdminController@catchAll')->where('other', '.*');
```

I get a 404 page.

Basically my routes file looks like:

```
$routeNamePrefix = 'coaster.admin.';
$adminUrl = config('coaster::admin.url') . '/';
// $adminController = '';
$nameSpace = 'Modules\Test\Http\Controllers';


Route::group(['prefix' => $adminUrl, 'middleware' => ['web', 'coaster.admin']], function () use ($adminUrl, $routeNamePrefix, $nameSpace) {

    Route::get('test', ['uses' => $nameSpace . '\TestController@getIndex', 'as' => $routeNamePrefix . 'system']);
    
});
```

My routes do work if I add them directly to the admin.php routes file.

```
$nameSpaceCore = 'Modules\Test\Http\Controllers';
Route::group(['prefix' => $adminUrl, 'middleware' => ['web', 'coaster.admin']], function () use ($adminUrl, $routeNamePrefix, $nameSpaceCore) {

    Route::get('test', ['uses' => $nameSpaceCore . '\TestController@getIndex', 'as' => $routeNamePrefix . 'system']);

});
```

But I really don't want to be editing your package routes like this.

I must be missing something, could you give me an idea or a heads up where to look next?

Thanks!

**Comment by neil-jennings** [comment]
Hi,

The coaster routes currently use multiple catchall's. One for the admin and another for the frontend, which would cause the admin redirect or 404.

If you call your provider before the CmsServerProvider your routes should be matched before the catch all in coaster.
Also If you want to use the admin url config setting in your routes you will need to load the config settings first which is possible with the CoasterConfigProvider.

So your providers file should look something like this:

CoasterCms\Providers\CoasterConfigProvider::class,   
YourModule\Providers\Provider::class,
CoasterCms\CmsServiceProvider::class,

**Comment by illuminate3** [comment]
Thanks! but ... Hmmm,

in app.php

```
        /*
         * Package Service Providers...
         */
        // CoasterCms\Providers\CoasterConfigProvider::class,
        Caffeinated\Modules\ModulesServiceProvider::class,
        CoasterCms\CmsServiceProvider::class,
```
* I'm not using the CoasterConfigProvider.

in Modules/Routes/web.php

```
Route::group(['prefix' => 'module/origami'], function () {
    Route::get('/', function () {
        dd('This is the Origami module index page. Build something great!');
    });
});
```

I then do the larval routine of route cache clear, composer dump, and call route:list, the route is listed.

When I hit: coaster.local/module/origami I still get a 404.

IF I drop that test route into the coaster package admin.php file at the end

```

Route::group(['prefix' => 'module/origami'], function () {
    Route::get('/', function () {
        dd('This is the Core module index page. Build something great!');
    });
});

// catch invalid admin routes
Route::any($adminUrl . '{other}', 'CoasterCms\Http\Controllers\AdminController@catchAll')->where('other', '.*');
```

I don't get the 404 ...

I've been slowly going through parts of your package but must be missing where the magic is happening for the verification of the route.

**Comment by chadanuk** [comment]
Hi,
I'm presuming you'll want the route to be an admin route? If not then I'd 

This whole area (around extending coaster simply) is something I intend to document soon as I have done a few Coaster sites with extended features.

You will probably need to look in the database. Admin route authentication uses the 'admin_actions' table in conjunction with the 'admin_controllers' table. 

Also, if you want to add an admin menu - you'll then need the admin_menu table.

Hopefully, that solves the problem.

**Comment by illuminate3** [comment]
@chadanuk Thanks for the extra information.

I'm using the caffeinated/module package and have had success previously with it.
https://github.com/caffeinated/modules

What I'm intending to do is eventually copy the pages part of the system to build a news system. but before that I figured I do a simple Test run first.

My routes are getting loaded.

```
|        | GET|HEAD                       | admin/test                                   | coaster.admin.test                        | Modules\Test\Http\Controllers\TestController@getIndex                               | web,coaster.admin |
|        | GET|HEAD                       | admin/themes                                  | coaster.admin.themes                       | CoasterCms\Http\Controllers\AdminControllers\ThemesController@getIndex                | web,coaster.admin |
```

From my trial and error approach is that I'm having trouble finding where the route is being into the system. The reason I think it's something prior to almost every where is that in the AdminAuth Middleware

```
$controller = !empty($routeParts[2]) ? $routeParts[2] : null;
```

is coming up null.

I'm starting to wonder if there is some kind of incompatibility issue going on or if coaster is overriding everything else ...

This works like you suggested if I drop it in larval's vanilla routes location.

```
Route::group(['prefix' => 'module/test'], function () {
    Route::get('/', function () {
        dd('This is the Test module index page. Build something great!');
    });
});
```

I even tried pull the PageController into it's own module too and like the test controller it redirects if I comment out the catchAll function, it will throw a 404. Because of this, I don't think it has anything to do with what is being returned by the database. The PagesController is already in there.


I appreciate all the help you all have been giving!

**Comment by illuminate3** [comment]
Did some more investigative work.

```
Route::any($adminUrl . '{other}', 'CoasterCms\Http\Controllers\AdminController@catchAll')->where('other', '.*');
```
```
Route::any('{other}', 'CoasterCms\Http\Controllers\CmsController@generatePage')->where('other', '.*');
```

If I turn both of those routes off, I'm getting into the admin and front end areas with no problems. and the controller name is being passed along. Any ideas where I should be looking to see where I could put in some logging / echoes to see what is causing my routes to bounce?

thanks!

**Comment by chadanuk** [comment]
I'm pretty sure this is to do with the order that the routes are being called if the  catch-all route happens before your routes then it will catch everything. 

If you try commenting the catch-alls in the admin/cms routes and copying and pasting those catch-alls under you routes, does that then work?

**Comment by chadanuk** [comment]
Here is my config/app.php Service Provider list (after Illuminate defaults) If that helps:


       CoasterCms\Providers\CoasterConfigProvider::class,
        App\Providers\AppServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        /*
         * Package Service Providers...
         */
        CoasterCms\CmsServiceProvider::class,
        /*
         * Application Service Providers...
         */
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,

The Config Provider is before the Route Provider this gives me control over the routes as I want them.

**Comment by chadanuk** [comment]
I'm going to close this, let us know if you have any further issues?
