### ISSUE TITLE
coaster_cms.local/admin/groups/edit/1

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#13]
Have example data in database.

Blogs > Edit Group Settings > error

```
Undefined variable: selectOptions (View: /Users/gigaByte/Sites/coaster/vendor/web-feet/coasterframework/resources/views/admin/blocks/select/main.blade.php) (View: /Users/gigaByte/Sites/coaster/vendor/web-feet/coasterframework/resources/views/admin/blocks/select/main.blade.php)
```

I tried digging through the blade files and a quick check seems to be not pulling in the data sent from the controller.

**Comment by tliesnham** [comment]
Hi illuminate3,

Thanks for pointing this out to us. We'll get on and see about getting this fixed.

Kind regards,

Taylor

**Comment by neil-jennings** [comment]
Hi illuminate3,

This is now fixed in the latest release.
