### ISSUE TITLE
File Manager - CMS Page not found

### ISSUE THREAD

**Issue by harrysbaraini** [Web-Feet/coastercms#14]
Hi, I'm testing Coaster to use it in the agency I work for. It has been an easy ride, but I am catching a CMS Page not found. I can open any other file type than .php in public/coaster folder on browser.

I'm running it on **Laravel Valet**, Laravel 5.3.

Thanks

**Comment by tliesnham** [comment]
Going on from what Neil said I also use Valet and have since made a driver that works with Coaster. Create a file named CoasterValetDriver.php within ~/.valet/Drivers and paste the following:

`<?php

class CoasterValetDriver extends ValetDriver
{
	/**
	 * Determine if the driver serves the request.
	 *
	 * @param string $sitePath
	 * @param string $siteName
	 * @param string $uri
	 * @return void
	 */
	public function serves($sitePath, $siteName, $uri)
	{
		return is_dir($sitePath.'/public/coaster/filemanager');
	}

	/**
	 * Determine if the incoming request is for a static file.
	 *
	 * @param string $sitePath
	 * @param string $siteName
	 * @return string|false
	 */
	public function isStaticFile($sitePath, $siteName, $uri)
	{
		if (file_exists($staticFilePath = $sitePath.'/public'.$uri)) {
			return $staticFilePath;
		}

		return false;
	}

	/**
	 * Get the fully resolved path to the application's front controller.
	 *
	 * @param string $sitePath
	 * @param string $siteName
	 * @param string $uri
	 * @return string
	 */
	public function frontControllerPath($sitePath, $siteName, $uri)
	{
		if (strpos($uri, '/coaster/filemanager') !== false)
		{
			return $sitePath.'/public'.$uri;
		}

		return $sitePath.'/public/index.php';
	}
}`
