### ISSUE TITLE
Edit page with video - error

### ISSUE THREAD

**Issue by yuri25** [Web-Feet/coastercms#18]
http://ptzw.ru/admin/pages/edit/8

Whoops, looks like something went wrong.

1/1
FatalErrorException in 7def214df381c084ec483630c87bd527b806f53b.php line 6:
Call to undefined method CoasterCms\Libraries\Blocks\Video::dl()
in 7def214df381c084ec483630c87bd527b806f53b.php line 6

The page itself is displayed normally,  http://ptzw.ru/services/cloud-control

How set on debug?

**Comment by neil-jennings** [comment]
Hi yuri25,

An error in the admin view for this block has been fixed in the latest release.

**Comment by yuri25** [comment]
Updated, thank you very much!
