### ISSUE TITLE
Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by PhillipMwaniki** [Web-Feet/coastercms#2]
Hello, 
   Every time I go through the installation process, there seems to be an issue with the database connection. I changed the details in the .env file plus also changed the data in config/database.php file.

**Comment by Chub97** [comment]
Hi Phillip,

You are correct in changing the database details within the .env file. You shouldn't need to make any changes to the config/database.php file, I'd recommend you revert any changes to ensure there aren't any issues further down the line.

The .env file is written to during the installation, therefore you shouldn't really need to change either of them beforehand. Which method did you use to install Coaster CMS?

Further installation documentation can be found at [](http://www.coastercms.org/documentation/developer-documentation).

Taylor.

**Comment by PhillipMwaniki** [comment]
Hi,
   My password starts with an exclamation mark, could that be marked as a probable cause ?

**Comment by Chub97** [comment]
I wouldn't think the exclamation mark would be causing a problem, although we will take a look into it.

It may be worth setting 'DB_HOST' as 127.0.0.1 instead of localhost. The thing that strikes us as being odd is that the original error seems to suggest that the password isn't being used.

**Comment by Chub97** [comment]
Have you had any luck resolving the issue?

**Comment by PhillipMwaniki** [comment]
Not yet. It seems there are issues with the dotfile being detected

**Comment by Chub97** [comment]
Did you install Coaster using Composer?

Can you see the installation pages within your browser?

**Comment by PhillipMwaniki** [comment]
Yeah I cn c the page and yes I do use composer. I use laravel at work and I hv  never had this problem. Can u try making an install on ur end ?

**Comment by Chub97** [comment]
I just set up an installation locally using Composer and the installation script seemed to work fine. Are you sure your database details are correct?

**Comment by PhillipMwaniki** [comment]
Yap, here is a copy of my env.local file 

APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:37VxYSE4DA3l0MWe2Nra88AEqaNTDYo+VU04K5dj55o=

DB_HOST=localhost
DB_DATABASE=coastercms
DB_PREFIX=ccms_
DB_USERNAME=root
DB_PASSWORD=!23qweASD

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

MAIL_DRIVER=mail
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

**Comment by Chub97** [comment]
Could you take a look at your install.txt file? It can be found within storage/app.

Do you know what versions of PHP and MySQL you are using within your development environment?

**Comment by PhillipMwaniki** [comment]
An interesting fact here is that I don't think that my .env file is being read, check out this error

> at PDO->__construct('mysql:host=;dbname=', '', '', array('0', '2', '0', false, false)) in Connector.php line 55
at Connector->createConnection('mysql:host=;dbname=', array('driver' => 'mysql', 'host' => '', 'database' => '', 'username' => '', 'password' => '', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'name' => 'mysql'), array('0', '2', '0', false, false)) in /var/www/html/coastercms/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php line 24

**Comment by PhillipMwaniki** [comment]
I'm using PHP 7 and MySQL 5.5.47. The install.txt file says add-tables. I'm on Linux Ubuntu Ver 14.04 LTS

**Comment by neil-jennings** [comment]
The install script needs to write to the .env file to store the database details.
It seems like there is not sufficient permissions to do this an leaves the .env file with empty values.
If you manually put the database details in the .env file it should work.

We are going to look at adding a permissions check on the install, including whether the .env file is writeable.

**Comment by PhillipMwaniki** [comment]
I changed the permissions to 755 on all files and didn't work and then I changed to 777 but nothing yielded. I used -R on both permissions.

**Comment by neil-jennings** [comment]
After running the database part of the install, try manually putting the database details in the .env file if they are not appearing. There might be something else stopping the .env file getting written to.

**Comment by PhillipMwaniki** [comment]
Yeah done that still no change. Kinda funny.

**Comment by chadanuk** [comment]
It's very strange - we've run multiple installs and we're all on different set ups (Mac/PC/Linux) so hard to say what the issue is... It might be worth looking in this file inside the vendor/web-feet/coasterframework directory and doing a bit of digging/debugging in there in the install process?
 
[https://github.com/Web-Feet/coasterframework/blob/master/src/Http/Controllers/Frontend/InstallController.php](https://github.com/Web-Feet/coasterframework/blob/master/src/Http/Controllers/Frontend/InstallController.php)

**Comment by PhillipMwaniki** [comment]
My problem seems to exist in the postIndex method. Nothing is passed to the $details variable.

**Comment by chadanuk** [comment]
Are you using apache or nginx or homestead? - That looks like it is related to a POST headers issue?

**Comment by PhillipMwaniki** [comment]
apache 2

**Comment by chadanuk** [comment]
It would be surprising if it was a config set up issue as I doubt this is the only thing you have running.. but it might be worth taking another look. We run the CMS on nginx and Apache 2 without issues.

I promise it will be worth it if you can get it running!

**Comment by PhillipMwaniki** [comment]
When I dd the post event from the browser I get this:

array:6 [▼
  "_token" => ""
  "host" => "localhost"
  "user" => "root"
  "password" => "!23qweASD"
  "name" => "coastercms"
  "prefix" => "ccms_"
]

Is the token supposed to be empty

**Comment by PhillipMwaniki** [comment]
I have been able to fix the issue by:
1) Set the permissions of the project folder to 777 (755) did not work
2) php artisan config:clear
3) php artisan config:cache
