### ISSUE TITLE
add comment - Error 

### ISSUE THREAD

**Issue by yuri25** [Web-Feet/coastercms#20]
http://ptzw.ru/blog/mytest#form28

Error: 500

Connection could not be established with host ptzw.ru [Connection refused #111]

Line 269 in /...../ptzw.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php

            throw new Swift_TransportException(
 

Full Trace:

#0 /...../ptzw.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 /....../ptzw.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 /...../ptzw.ru/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /...../ptzw.ru/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(374): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /...../ptzw.ru/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(196): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /...../ptzw.ru/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\Mail\Mailer->send('themes.coaster2...', Array, Object(Closure))

**Comment by yuri25** [comment]
also add a user error persists
https://github.com/Web-Feet/coastercms/issues/19#issuecomment-264301565

**Comment by neil-jennings** [comment]
This is to do with the mail configuration as with #19 , a notification mail gets sent when a comment is made.

**Comment by yuri25** [comment]
Problem solved. Add to .env MAIL_DRIVER = "sendmail"
Thank you so much.
