### ISSUE TITLE
Problem with show features in default theme

### ISSUE THREAD

**Issue by HACKHERS** [Web-Feet/coastercms#22]
Hey, there is a problem when you disable showin features it looks like this: https://i.imgur.com/QeE0T5a.png

It shouldn't print `<section id="sec2"></section>` because It's not going to write anything in it.

**Comment by neil-jennings** [comment]
This is just the was the theme has been designed, if you want to remove the grey bar at the bottom when disabling features you can make a quick edit to the theme.

Find /resources/views/themes/coaster2016/sections/footer.blade.php
And move the section tags inside the if statement at the top.
