### ISSUE TITLE
template:section:footer

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#24]
I don't know if I pooched this on install or when I edited it directly but for some reason, the footer template is being real stubborn and does not want to be edited in the theme editor while working online.

I have run the block updates and various versions that a normal user would go through. I also made all the templates 777, deleted that file and copied the header file and pasted back in the footer HTML. I also tried removing the js that is in the template.

Strange thing is that either the template is empty or it just won't show in the admin area.

Straight editing through FTP does work.

Any ideas or have you seen this happen before?

**Comment by chadanuk** [comment]
Hi @illuminate3 

I've fixed this in the core code (release to follow). It was jQuery finding the script tags and for some reason trying to process them when populating the textfields of the editor. Resorted to using plain js and problem disappears.
