### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by cool14521** [Web-Feet/coastercms#27]
php -v
PHP 7.0.1 (cli) (built: Dec 16 2015 13:32:55) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.0RC3, Copyright (c) 2002-2015, by Derick Rethans

php vendor/web-feet/coasterframework/updateAssets

Coaster Framework: Updating ACE HTML/CSS/Code Editor .

  [GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/l
  ibcurl-errors.html)

**Comment by chadanuk** [comment]
Hi, 

The only thing I can find on this that might help is here...
http://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate

Let us know how you get on....

**Comment by chadanuk** [comment]
If you're on windows then take a look at this blog, it might help...
https://www.coastercms.org/blog/installing-coaster-cms-windows/
