### ISSUE TITLE
File Manager - No input file specified

### ISSUE THREAD

**Issue by gkouk** [Web-Feet/coastercms#3]
Hello,
first of all I want to congratulate you for the excellent work you have done! I installed your CMS and all are OK except the file manager option in backend. When I choose File Manager I get the message "No input file specified." and nothing is displayed. I send you a capture image with this issue. Could you help me with this please?
Thanks in advance,
George

![capture](https://cloud.githubusercontent.com/assets/4380294/15742748/7d0f6d7c-28c9-11e6-9afc-59ea2c952045.jpg)

**Comment by neil-jennings** [comment]
Hi George,

Glad you like Coaster, I've had a little look into the issue.

The filemanager is loaded in an iframe which should then load the file:
htttp://coastercms.local.dev/coaster/filemanager/dialog.php

It seems something is stopping PHP loading that file. Maybe there's a permissions issue with the file or directories ?

Neil

**Comment by gkouk** [comment]
Hi Neil,
thanks for your reply. The problem is that there isn't any file manager folder under public/coaster. Also there are not any jquery & jquery-ui folders too, under the same folder public/coaster. Probably this is an installation issue, or something else with my homestead environment. Certainly I don't know if there is still some lack of files or folders. I will download code from https://www.coastercms.org/download and copy these folders manually.
Regards,
George

**Comment by tliesnham** [comment]
Hi George,

There is currently a weird permissions issue occurring when using Coaster with Homestead. When working on a local installation changing all occurrences of 'unlink' to '@unlink' within _vendor/web-feet/coasterframework/updates/publicAssets.php_ seems to act as temporary fix. After this when running the _composer update_ command all additional files should install correctly.

Hopefully we will come up with a more permanent solution in the future.

Regards,
Taylor

**Comment by gkouk** [comment]
Hi Taylor,
thank you for your concern, I will try it.
Regards,
George

**Comment by gkouk** [comment]
Hello again,
you were right Taylor, it was Homestead issue, when I changed all occurrences of 'unlink' to '@unlink' and run composer update, all operated well!
I would like to ask you one more thing: could I possibly add an admin theme template for L5 to your beautiful CMS (Josh - Laravel Admin Template)?
Thank you in advance,
George

**Comment by tliesnham** [comment]
Hi George,

Glad that solved the problem.

At the moment there isn't any quick way of adding a custom admin theme, in the case of Josh we don't currently have any builtin support for server monitoring tools or analytics. Therefore it may take quite a bit of work to get all of the features working.

Regards,
Taylor

**Comment by gkouk** [comment]
Hi Taylor,
thanks for your reply, I understand your point. I will try to merge this theme.
Regards,
George

**Comment by gkouk** [comment]
Hello again,
could I ask you one last question? I see that there is a lang folder under resources, so I assume that there is a language module. Is this only for messages (pagination, validation, etc.) or it could be used for cms content too (pages, menus, etc.)? I mean could I have a 2 language front-end UI with your cms?
Finally, do you have any documentation for your cms?

Thank you in advance,
George

**Comment by tliesnham** [comment]
Hi George,

Multi-languages are supported on the frontend. However, the text in the admin is hard-coded and doesn't use the lang folder. To add multi-language support to the frontend you need to add an additional language to the languages table within the database.

We do have documentation available, we should probably add this to GitHub. Thanks for pointing it out to us.

https://www.coastercms.org/documentation

Regards,
Taylor

**Comment by gkouk** [comment]
Thank you very much Taylor!

**Comment by tliesnham** [comment]
Hi George,

Sorry for the late reply, I didn't seem to get a notification about analytics.

We don't currently have any analytics based documentation for Coaster at the moment, but we may add some stuff in the future.

Regards,
Taylor

**Comment by gkouk** [comment]
Hi Taylor,
sorry for my bad phrase "analytic"! I meant more detailed developer documentation.

regards,
George

**Comment by tliesnham** [comment]
Hi George,

Unfortunately, we don't have any more detailed developer documentation as of now. We will get round to adding what all the different classes and functions do at some point in the near future.

Regards,
Taylor
