### ISSUE TITLE
cUrl error 60 during installation on WAMP

### ISSUE THREAD

**Issue by Rwthwyn** [Web-Feet/coastercms#31]
Hi there,

I've been following your instructions for setting up Coaster CMS - which, by the way, is the only CMS I have so far found that requires Laravel 5.3, so well done! I'm setting it up on top of a Laravel installation that also has Laravel Spark in place. So, I don't know if that has caused the issue. I'm running the installation on WAMP.

Running the script:

`php vendor/web-feet/coasterframework/updateAssets`

results in an error, specifically, `cUrl error 60:SSL certificate problem.`

Do you know what might be causing this problem or, a solution to it?

Many thanks in advance for your help.

With kind regards,

Mark

**Comment by neil-jennings** [comment]
There are issue on windows downloading files using https with curl.

You can fix this by downloading http://curl.haxx.se/ca/cacert.pem 
Then set the curl.cainfo var in php.ini to where you downloaded it, ie.
curl.cainfo = "C:\xampp\php\extras\ssl\cacert.pem"

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks very much for your swift reply.

I downloaded the cacert.pem and have edited php.ini as you suggested. However, this has not fixed the problem.

The relevant line in php.ini reads as follows:

`curl.cainfo ="C:/wamp64/bin/php/php7.0.0/extras/ssl/cacert.pem"`

I realise my path doesn't exactly match yours, so, could that be the error? Otherwise, is there anything else you can suggest?

With kind regards,

Mark

**Comment by neil-jennings** [comment]
It doesn't have to be the same path, just as long as you've put the cacert.pem file at that location you specified. Also make sure there is no semi colon in front of the line to comment it out.

You might need to restart/reload the php service for the change to take effect but there shouldn't be anything else required to fix this issue normally.

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks for all your help.

It doesn't look like it's going to work. I think I'm just going to have to abandon my attempt at trying to install Coaster CMS on WAMP.

With kind regards,

Mark
