### ISSUE TITLE
Error whilst installing Coaster via command line on live server

### ISSUE THREAD

**Issue by Rwthwyn** [Web-Feet/coastercms#32]
Hi there,

I've decided to have a go at installing Coaster CMS alongside Laravel Spark on a live server, using the command line and following the instructions found here: [https://www.coastercms.org/documentation/developer-documentation](https://www.coastercms.org/documentation/developer-documentation).

It's a similar issue to [that which I experienced with WAMP server](https://github.com/Web-Feet/coastercms/issues/31), in that the process fell over at the same point.

This time, I ran the script

`php vendor/web-feet/coasterframework/updateAssets`

which resulted in the following error:

`[ErrorException]
copy(/var/www/vhosts/example.co.uk/laravel-b-coast/public/ace/mode-html_blade.js): failed to open stream: No such file or directory`

Not sure how to fix this. So, any pointers would be most useful. I've had a look at the folder tree and there is a folder `/ace` that's been created under `/public/coaster` but nothing under `/public`. Should I have created this myself?

With kind regards,

Mark

**Comment by neil-jennings** [comment]
It's possible some symlinks may be causing this issue as the code runs a realpath on the copy from location.

The copying of the file should be done from a file in the vendor package to the public folder:
/vendor/web-feet/coasterframework/public/ace/mode-html_blade.js
/public/coaster/ace/mode-html_blade.js

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks for getting back to me so quickly.

I've had a look and `mode-html_blade.js` is at `/vendor/web-feet/coasterframework/public/ace/mode-html_blade.js`

> It's possible some symlinks may be causing this issue as the code runs a realpath on the copy from location.

How do I solve that issue?

Also, at some point, shouldn't I be running a `php artisan migrate` command to populate the site's database with Coaster tables?

With kind regards,

Mark

**Comment by neil-jennings** [comment]
You could try changing this line locally and removing the realpath function.
https://github.com/Web-Feet/coasterframework/blob/master/updates/publicAssets.php#L66

The only reason I could think that it would be failing is that realpath function with symlinks, other than that it's pretty must just a string path.

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks again for your help.

I don't know what's going wrong with the install process, but I keep encountering errors. It seems it's nearly time to abandon the attempt at installing Coaster CMS.

To solve the original error, I created the directory `/ace` under `/public` and ran the

`php vendor/web-feet/coasterframework/updateAssets`

command again. This told me that the directory `public/jquery/tinymce` didn't exist, so I created that. After running the above command again, THIS TIME, I encountered no errors. According to the instructions, all that remained was this:

> 5. Add the service provider CoasterCms\CmsServiceProvider::class to your config/app.php file.

which I did. That's the last instruction under the Development Documentation. So I turned to the User Docs, which said I should just have to visit http://example.co.uk/admin and I would see a login screen. Would that were the case. Instead, I see a screen that says,

> Whoops, looks like something went wrong.

and gives an error:

> ErrorException in Filesystem.php line 111:

I figured that perhaps I should have run the

`php artisan migrate`

command to add any necessary tables to the database first, but this threw this error:

`[ErrorException]
  file_put_contents(/var/www/vhosts/example.co.uk/laravel/storage/app/coaster/install.txt): failed to open stream: No such file or directory`

Something's going wrong, and I don't know what. It seems to me that it could be user error - this sort of thing usually is - or either the instructions for installation are lacking some commands or Coaster CMS is missing key files.

Whichever, I'm sorry to say that despite your generous help, I may have to give up on Coaster CMS.

With kind regards,

Mark

**Comment by neil-jennings** [comment]
Does the error give any more details on the Filesystem error ?

The install should create the folders required and do the migration, though you can try adding the coaster folder manually and that might fix it.
/storage/app/coaster

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks again for your extremely quick reply.

That FileSystem error does go in to a lot more detail, and later on today I'll upload a screen grab for you to look at, if you like.

With kind regards,

Mark

**Comment by Rwthwyn** [comment]
Hi again,

Right, I tried again from scratch, and this is exactly what I did:

Starting on WAMP, I set up a fresh install of Laravel. Then, still on WAMP, added Laravel Spark with Braintree. Once I'd established that that was all working, I zipped the whole lot up, uploaded it to the server, where I unpacked it to a new directory.

Now, using Putty, I followed the instructions at https://www.coastercms.org/documentation/developer-documentation with some additions, like so:

Instructions 1 and 2, fine. BUT at instruction 3 I need to create an additional directory `/public/ace`.

So, instruction 4 then works ... mostly. At this point I need to manually create a new directory `/public/jquery/tinymce` which, when I follow instruction 4 again, it completes.

Instruction 5, easy to do. But, at that point the instructions run out. With other Laravel apps that use a database, there is a `php artisan migrate` command, so I run that. Initially that says that the `/storage/app/coaster` directory is missing, so I create that. Running the command again results in the following errors:

> [Illuminate\Database\QueryException]
>   SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'performance_indicators' already exists (SQL: create table `performance_indicators` (`id` int unsigned not null auto_increment primary key, `monthly_recurring_revenue` decimal(8, 2) not null, `yearly_recurring_revenue` decimal(8, 2) not null, `daily_volume` decimal(8, 2) not null, `new_users` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

and: 

>  [Doctrine\DBAL\Driver\PDOException]
>  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'performance_indicators' already exists

and:

>  [PDOException]
>  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'performance_indicators' already exists

I find this a bit confusing, but wonder if the creation of the `/storage/app/coaster` has helped anything, so visit http://sypotest13.co.uk/admin in a browser and there's _no error_ BUT, it says something about permissions need granting on a few directories. So, back in Putty, I execute:

`chown -R sypotest13-maste:psaserv laravel`

which fixes the issue. So far so good. There's another screen - I think - and then another is http://sypotest13.co.uk/install/database-save At this point I'm starting to think that maybe Coaster CMS will finally work. But, clicking on the, 'Run Database Setup,' button tells me that:

> can't write settings to the .env file, check it is writable for the installation

which is a bit strange, as after running the `chown` command, an earlier screen had told me that the `.env` file **was** writable.

I really don't understand what needs to be done to fix this. I've deliberately added the links above to the live screens so you can have a look at what's happening yourself. However, these links will only be current for the next half an hour as I am switching back to an installation that just has Laravel Spark on it, as the core of the project we're working on is to do with that instead.

With kind regards,

Mark

**Comment by neil-jennings** [comment]
With the migrations it looks like it was more than the coaster ones being run, to run just the coaster ones a path needs to be set.
php aritsan migrate --path=vendor/web-feet/coasterframework/database/migrations

With the .env error it seems there's a key generate being called which could be throwing the error.


Coaster has a catch all in it's routes which may cause issues with Spark unless you add the Spark provider first.

**Comment by Rwthwyn** [comment]
Hi Neil,

Thanks for your reply and for continuing to help.

This is something I may be returning to, but, temporarily at least, I'm going to have abandon Coaster CMS.

With kind regards,

Mark

**Comment by 0E800** [comment]
I have similar problems with installing Coaster CMS from composer.

Installation goes smoothly without errors, however when I login to the admin panel and go to manage themes, the theme preview images do not show.
Nginx: error:
`48 open() "/var/www/laravel/public/cache/coaster/tmp/themes/default/screenshot-252x142.jpg" failed (2: No such file or directory)`

When I look inside public/cache/ there are no other folders or files.

**Comment by chadanuk** [comment]
See response #58
