### ISSUE TITLE
How would you go about implementing a general search

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#33]
I was wondering where I should be looking to expand the search function from just the blog to all pages.

Thanks!

**Comment by neil-jennings** [comment]
To pass a search query to a page to begin a search you can put the query in the url ie.:
.../{page_url_segment}/search/{query}    (if page_url_segment = "search" then it's just .../{page_url_segment}/{query}  )
.../{page_url_segment}?q={query}           (or can use post value for q)

Then the search page you create will need to use a template with the function (below) inside it.
`PageBuilder::search(['view' => 'default'])`

This function will return a categorised view of the pages found via the search query.

**Comment by illuminate3** [comment]
Sorry about getting back to you so late.

I tried what you suggested ... either I'm dense or I didn't implement this correctly.

I want to cover several segments: information, events, news, blog and any single pages

I copied and renamed several of the blog templates and named them: search, search-search, search-post, search-category

I then doubled the footer javascript bit and copied, changed up the blog search form and pasted it into the header.

I also duplicated, renamed the search page found in the blog group and moved it up the tree.

Of course, I did the theme checkbox thingy.

I'm gonna keep trying some ideas ... but I'd appreciate any input.

Thanks!

**Comment by neil-jennings** [comment]
Are you getting any results back ? 

On the results page I would check the searchQuery exists, you can check it with:
`PageBuilder::getData('searchQuery')`

And then just make sure the inbuilt search function that returns the results is somewhere on the template the results page is using.
`PageBuilder::search()`

Also if you just want to search pages that are using a specific template like the news template you can filter the returned results by template ids. ie. if the news template has the id 4 you can do:
`PageBuilder::search(['templates' => [4]'])`

**Comment by illuminate3** [comment]
Thanks for your help, but I'm still busting a nut on this ...

I'm not planning on using the blog function but I've left it in because I thought it would be good to have a reference point.

the word "kensaku" means "search" in Japanese. I also didn't want to use possible system terms like content, page, or what ever.

footer.blade
`                $('#blogSearch').submit(function(event) {
            event.preventDefault();
            window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('blog_search_page')) }}/'+$('#query').val();
        });

        $('#kensakuSearch').submit(function(event) {
            event.preventDefault();
            window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('kensaku_search_page')) }}/'+$('#kensaku').val();
        });
`

Which converts to 
`
$('#blogSearch').submit(function(event) {
            event.preventDefault();
            window.location.href = '/blog/search/'+$('#query').val();
        });

        $('#kensakuSearch').submit(function(event) {
            event.preventDefault();
            window.location.href = '/kensaku/'+$('#kensaku').val();
        });

`

menu.blade
`    <form id="kensakuSearch">
        <div class="input-group">
            <input type="text" id="kensaku" placeholder="Search" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" id="kensakuSearchButton" type="submit"><span class="fa fa-search"></span></button>
            </span>
        </div>
    </form>
    <form id="blogSearch">
        <div class="input-group">
            <input type="text" id="query" placeholder="Search" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" id="blogSearchButton" type="submit"><span class="fa fa-search"></span></button>
            </span>
        </div>
    </form>
`
I am getting results with the blogsearch but not for the full site search.

copy pasted blog-search.blade to kensaku-search.blade

`{!! PageBuilder::section('head') !!}

<div class="jumbotron" style="background: url({{ PageBuilder::block('internal_banner', ['view' => 'raw']) }}) no-repeat center"></div>

<?php $searchQuery = PageBuilder::getData('searchQuery');?>

<section id="sec1">
    <div class="container">

        {!! PageBuilder::breadcrumb() !!}

        <div class="row">

            <div class="col-sm-9">

                <h1>{!! PageBuilder::block('title') !!}: {{ $searchQuery ?: 'None' }}</h1>
                <p class="lead">{!! PageBuilder::block('lead_text') !!}</p>
                {!! PageBuilder::block('content') !!}

                <?php $pages = PageBuilder::search(['view' => PageBuilder::block('category_view'), 'groups' => [1], 'renderIfEmpty' => false]);?>
<?php
// $pages = PageBuilder::search(['view' => 'default']);
?>
                @if ($pages)
                    {!! $pages !!}
                @else
                    <div class="row">
                        <div class="col-sm-12">
                            <p>&nbsp;</p>
                            <p>No posts found.</p>
                        </div>
                    </div>
                @endif

            </div>



    <h3>Search</h3>

    <form id="kensakuSearch">
        <div class="input-group">
            <input type="text" id="kensaku" placeholder="Search ..." class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" id="kensakuSearchButton" type="submit"><span class="fa fa-search"></span></button>
            </span>
        </div>
    </form>


            <div class="col-sm-3">
                {!! PageBuilder::section('search-bar') !!}
            </div>

        </div>

    </div>
    
</section>

{!! PageBuilder::section('footer') !!}`

I did change the blog-bar to search-bar but that shouldn't be a problem.

On the admin side, I duplicated the search page that was located within the blog group and then moved it to a top page level.

I copied pasted the blog-category.blade to kensaku-category.blade but the duplicated page for the category view option does not see it. I've selected a default option and the blog option with no change.

For the template management in the blocks section I do see kensaku_search_pageand have it set to blog and the proper page is selected.

When I do a search from the header form: I get a 404 error and the url looks like http://coaster.local/kensaku/article  I do not have any nested pages for kensaku, just the one page.


What I tried to do was to copy the blog search and apply it to all pages and not just blog pages.

**Comment by illuminate3** [comment]
ugh ... formating is getting wacked to all hell ... ugh ...

**Comment by illuminate3** [comment]
ok. gonna answer my own question here but would still like advice.

I took Neil's advice and did this in my kensaku-search.blade


>// $pages = PageBuilder::search(['view' => PageBuilder::block('category_view'), 'groups' => [1], 'renderIfEmpty' => false]);
>
>$pages = PageBuilder::search(['view' => 'default']);

and then in the footer.blade

I changed the "/"

>            window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('kensaku_search_page')) }}/'+$('#kensaku').val();

to "?q="

>             window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('kensaku_search_page')) }}?q='+$('#kensaku').val();


It's working but I'm still wondering if I'm going about this the right way?

Thanks Neil!

**Comment by illuminate3** [comment]
hmmm, working with a big data set I found out that pagination breaks the search query.

page 1 with several pages remaining: "site.com/search?q=aid" 
page 2 ends up with : "site.comt/search?page=2" ... 

any ideas?

**Comment by neil-jennings** [comment]
I've made a change in the latest version of the coaster framework so pagination links in the search or category views will have existing query params appended.

Also there was bug getting the search string from the url path if the last cms page url segment was not 'search' which should be fixed in the latest version.

So if PageBuilder::block('kensaku_search_page') != 'search' then this should work now:
`window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('kensaku_search_page')) }}/search/'+$('#kensaku').val()`

Or if PageBuilder::block('kensaku_search_page') == 'search' :
`window.location.href = '{{ PageBuilder::pageUrl(PageBuilder::block('kensaku_search_page')) }}/'+$('#kensaku').val()`

**Comment by illuminate3** [comment]
Thanks Neil!

That fixed the paging issue.

I'm gonna close this since I seem to have everything working good enough.

thanks for all the help!
