### ISSUE TITLE
Demo page/data carousel :: caption wrecks havok on the image

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#35]
I'm still trying to figure out what the is causing the caption to push the height of the visible area of the banners.

Basically if you have the same image for 2 slides: the first slide has 1 line of text and the second slide has 2 lines of text. The image will repeat itself.

currently in the carousel.blade I've been tweeking the code like this:

`      <div class="item {{ ($count==1)?'active':'' }}" style="background:url('{{ PageBuilder::block('slide_image', ['view' => 'raw']) }}') no-repeat center center;background-size: cover; height: 65vh;">

                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <{{ ($count == 1)?'h1':'h2' }}>{{ PageBuilder::block('slide_title') }}</{{ ($count == 1)?'h1':'h2' }}>
                        <p>{!! PageBuilder::block('slide_text') !!}</p>
                        @if (PageBuilder::block('slide_button_link') != '')
                            <button class="btn btn-default" id="scrollbutton">{{ PageBuilder::block('slide_button_text') }}{!! PageBuilder::block('slide_button_icon')?' &nbsp; '.PageBuilder::block('slide_button_icon'):'' !!}</button>
                        @endif
                    </div>
                </div>

        </div>
`

I have added to the inline style and removed the container div.

Notice that I deleted the else code. I did that because it would show a button even if the button text and link is empty. I also changed the == to !=

Actually, I just commented out that area but github is giving me grief over Blade notation.

If I come across a solution I will post back.

**Comment by neil-jennings** [comment]
The only difference between the first slides and the rest should be the title tag, h1 on the first slide and h2 on the rest:
`($count == 1)?'h1':'h2'`

**Comment by illuminate3** [comment]
Hmm, Your demo site does the same thing. The image will repeat itself. I have a feeling that this might have something to do with the image being used as a background which would make some sense why the div will get jumpy.

**Comment by illuminate3** [comment]
Here's what I did with the blade.

>         <div class="item {{ ($count==1)?'active':'' }}">
            <img class="first-slide" src="{{ PageBuilder::block('slide_image', ['view' => 'raw']) }}" alt="{!! PageBuilder::block('slide_text') !!}">
            <div class="container">
                <div class="carousel-caption">
                    <{{ ($count == 1)?'h1':'h2' }}>{{ PageBuilder::block('slide_title') }}</{{ ($count == 1)?'h1':'h2' }}>
                    <p>
                        {!! PageBuilder::block('slide_text') !!}
                    </p>
                    <p>
                        @if (PageBuilder::block('slide_button_link') == '')
                            <button class="btn btn-default" id="scrollbutton">
                                {{ PageBuilder::block('slide_button_text') }}{!! PageBuilder::block('slide_button_icon')?' &nbsp; '.PageBuilder::block('slide_button_icon'):'' !!}
                            </button>
                        @else
                            <a href="{!! PageBuilder::block('slide_button_link') !!}" class="btn btn-default">
                                {{ PageBuilder::block('slide_button_text') }}{!! PageBuilder::block('slide_button_icon')?' &nbsp; '.PageBuilder::block('slide_button_icon'):'' !!}
                            </a>
                        @endif
                    </p>
                </div>
            </div>
        </div>


ugh github is really busting my nutz ... sorry about the bad formating

**Comment by illuminate3** [comment]
opps forgot the CSS

`
/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

.carousel {
	margin-top:-20px;
	height: 500px;
	margin-bottom: 0px;
}
.carousel-caption {
	z-index: 10;
}
.carousel .item {
	height: 500px;
	background-color: #777;
}
.carousel-inner > .item > img {
	position: absolute;
	top: 0;
	left: 0;
	min-width: 100%;
	height: 500px;
}
.carousel h1, .carousel p, .carousel h2{color:#fff; font-family: 'Open Sans', sans-serif; font-weight:300;}
.carousel h1, .carousel h2{font-size:60px; margin:30px 0;}
.carousel .item{padding:200px 0; background: #333; margin:0; text-align:center;}
.carousel p{font-size:20px;}
.carousel .fa{color:#fff !important;}
.carousel .btn{background:none; border-color:#fff; color:#fff;}

`

**Comment by neil-jennings** [comment]
The image will repeat itself again below if there is enough lines of text in the demo theme, there's no measures to limit text yet in the admin.

Though if you want to allow more text or varying amounts of text from the design side of things you can just reduce the padding the on the carousel item and set a larger fixed height.
`.carousel .item{padding: 100px 0; height: 700px;}`

**Comment by illuminate3** [comment]
Thanks,

Why did you make the image a background instead of doing it the normal bootstrap way?

**Comment by neil-jennings** [comment]
I didn't do the 2016 design myself, though I think it's just personal preference and maybe you can do a bit more with background images using css.

**Comment by illuminate3** [comment]
Possibly!

I'm gonna close this since the blade code above is working and the CSS will need some tweeking for being a little more reflexive.
