### ISSUE TITLE
Search multiple page groups

### ISSUE THREAD

**Issue by alkazar1957** [Web-Feet/coastercms#39]
Me again
Trying my damnest to understand the search. Seems to only search the category of pages that the search form is in? Is this correct? How would I expand the search to automatically search any group pages created?
Just trying to work my way through the search and I bodged the pagebuilderinstance.php adding 
           $options['groups'][0] = '1';
            $options['groups'][1] = '4';
            $options['groups'][2] = '3';
which returned found keywords from those groups but if I added a fourth item to the array it only searched and returned found keywords from the first array item even though when using only three items in the array it returned found keywords from all three groups.

Cheers.

Ken.

**Comment by alkazar1957** [comment]
Forgot to say this is front end.

Ken.

**Comment by neil-jennings** [comment]
Hi Ken,

I've had a look and can't see anything that would break the search from filtering on 4 groups rather than 3 as it's just a simple WhereIn query used.

If you try changing the groups selected in the template (ie. blog-search.blade.php in the coaster2016 theme) rather than directly in the pagebuilderinstance that might make some difference.

`<?php $pages = PageBuilder::search(['view' => PageBuilder::block('category_view'), 'groups' => [1], 'renderIfEmpty' => false]); ?>`

**Comment by alkazar1957** [comment]
That line is already in that blade. I put the search box on the front page and a search only returns one match. Same search on blog page returns one match. Same on other groups e.g. Articles, News etc.
Adding to the array as above returns three matches, one from each group.

Next? lol. Ain't this fun.

Ken.

**Comment by neil-jennings** [comment]
If you want to search everything just remove the groups filter from the results page:
`<?php $pages = PageBuilder::search(['view' => PageBuilder::block('category_view'), 'renderIfEmpty' => false]); ?>`

It's the results page code that determines the filters, the form only passes the query.

So if you only want to search pages that are in a group, or might be in a list of groups add
`'group' => [1, 2]` (where 1, 2 are group ids)
Again if you only want to search pages with certain templates you can add 
`'templates' => [1, 2]` (where 1, 2 are template ids)

**Comment by alkazar1957** [comment]
Just slapped my head and have gone to sit in the corner :(
