### ISSUE TITLE
Issues with permissons

### ISSUE THREAD

**Issue by akchamczuk** [Web-Feet/coastercms#4]
Hi there - I have been having problems with permissions and I'm not sure if there is something I have missed (your installation documentation is extremely limited; especially for new users like myself).

- I have made a clean install using composer.
- Made sure all the roots and .htaccess files are correct for apache2 etc.  
- I have changed all the folders in storage/ and bootstrap/cache to have read/write permissions (777).
- created an empty database (name) in MySQL / made sure database side is ready to go.

When running the setup, I get past the database connection prompts and I get the following error....

Exception in Local.php line 104:  Impossible to create the root directory "/var/www/cms-kissngo/public/cache".

I tried manually creating the folder and then I get other permission errors (so I know it has to be some permission setup)

ErrorException in KeyGenerateCommand.php line 58:  file_put_contents(/var/www/cms-kissngo/.env): failed to open stream: Permission denied

I am note very familiar with Linux / Apache / Web Server setups etc.  Based on your very short installation instructions - I know you may have made basic assumptions.  Can you please clarify if there are any other locations that the permissions need to be modified.  Thank-you.

**Comment by neil-jennings** [comment]
Hi,

The following two locations you mentioned will need write permissions:
/var/www/cms-kissngo/public/cache (whole directory)
/var/www/cms-kissngo/.env  (write permissions just needed on install)

I think it does depend on your default permissions but we will look at updating the install documentation to include these locations.

Regards,
Neil

**Comment by akchamczuk** [comment]
Gotten to the Theme installation and have hit another permission problem.

ErrorException in Theme.php line 199: ZipArchive::extractTo(): Permission denied
 1. in Theme.php line 199 
2.  at HandleExceptions->handleError('2', 'ZipArchive::extractTo(): Permission denied', '/var/www/cms-kissngo/vendor/web-feet/coasterframework/src/Models/Theme.php', '199', array('themeZip' => 'coaster2016.zip', 'filePathInfo' => array('dirname' => '.', 'basename' => 'coaster2016.zip', 'extension' => 'zip', 'filename' => 'coaster2016'), 'uploadTo' => '/var/www/cms-kissngo/resources/views/themes/', 'themeDir' => '/var/www/cms-kissngo/resources/views/themes/coaster2016', 'error' => '', 'zip' => object(ZipArchive), 'extractItems' => array(), 'i' => '62')) 

I added permissions to ..,/coasterframework/src/Models/ and all its files, and I still get the same error.

**Comment by neil-jennings** [comment]
I think as you installed using sudo the web user probably doesn't have any write permissions by default.

I would try giving write permissions to the folders in the public directory:
/var/www/cms-kissngo/public/cache
/var/www/cms-kissngo/public/coaster (may need to be created if this one if it doesn't exist)
/var/www/cms-kissngo/public/themes
/var/www/cms-kissngo/public/uploads

We have plans on creating a permissions checker on the install within the next few versions to solve these problems.
Currently posted as an issue on the framework: https://github.com/Web-Feet/coasterframework/issues/12

**Comment by akchamczuk** [comment]
That seems to have solved the issue - Thank-you.  As a side note, you might also want to make sure that 'upgrading' through web admin is also added to you list for 'permissions checking' as it has problems there as well.

Thank-you for all your help.
