### ISSUE TITLE
How can I pull in information that is stored in the page but that isn't in the page_lang table?

### ISSUE THREAD

**Issue by illuminate3** [Web-Feet/coastercms#40]
In a page I have loaded a variable on the fly: example summary.

in the category template:

```
@if ($is_first || in_array($count-1, $new_col_on_count))
    <div class="col-sm-4">
        <ul>
            @endif
            <li><a href="{!! $page->url !!}">{!! $page->name !!}</a>{!! $page->summary !!}</li>
            @if ($is_last || in_array($count, $new_col_on_count))
        </ul>
    </div>
@endif
```
You can only access the $page object. I tried $page->summary and obviously it errored out. Is it possible to do what I'm trying to do and if so where should I be looking to to merge a data call?

thanks guys!

**Comment by chadanuk** [comment]
Hi, 

If you need block data, you can use:
` PageBulder::block('summary') `

as the PageBuilder knows what page you're on inside a category view.

Otherwise - if you need something from the Page model - try this...
`$page->page->summary?`

**Comment by illuminate3** [comment]
The PageBuilder call worked but $page-page->summary didn't it only came up empty.

Thanks!
