### ISSUE TITLE
Fresh install - File manager not found

### ISSUE THREAD

**Issue by andykarczewski** [Web-Feet/coastercms#42]
Just did a clean install on my local machine, everything works fine but when I go to the File Manager section in Admin, it shows an iframe 404 not found page.
Edit: Using Laravel Valet. Just googled and saw there's a custom Driver for it which now solves the issue.
Might be worth adding that into the docs on your site?

**Comment by chadanuk** [comment]
Thanks @andykarczewski we will get that added!
