### ISSUE TITLE
Installation error new version 5.4

### ISSUE THREAD

**Issue by envobe** [Web-Feet/coastercms#45]
Hi, I am getting the following error during the installation phase. I ask you to help. 
Best regards.
![1](https://cloud.githubusercontent.com/assets/5060075/26780322/eba61444-49f1-11e7-9513-9d3cb44a944f.PNG)

**Comment by neil-jennings** [comment]
Hi envobe,

This looks like a query issue with some stricter versions of Mysql.
I've updated the coasterframework package with a fix for this, so you just need to run a composer update.

**Comment by envobe** [comment]
Hi,

I made an update, but I get the same error again. Thank you.
![ekran alintisi](https://cloud.githubusercontent.com/assets/5060075/26782834/0d40390c-49fe-11e7-85a5-96c6b9e6f77f.PNG)
![hata](https://cloud.githubusercontent.com/assets/5060075/26782842/1619f702-49fe-11e7-86e7-dcf2d3931dce.PNG)

**Comment by neil-jennings** [comment]
There was a naming issue in the frameworks version tag. (stray dot)
Try another update it should download now.

**Comment by envobe** [comment]
Thank you, I have accomplished the installation successfully. But when adding or correcting the page I get the error in the image.
![ekran alintisi](https://cloud.githubusercontent.com/assets/5060075/26783876/25e96e1a-4a03-11e7-97cd-c06e6f9c1607.PNG)
@neil-jennings

**Comment by neil-jennings** [comment]
It's seems it's an issue with the "having" clause pre Mysql 5.7 . 
I will have a look into rewriting that query to support earlier versions.

**Comment by neil-jennings** [comment]
This should be fixed in the latest version of the framework now.
