### ISSUE TITLE
Database error, settings table could not be found.

### ISSUE THREAD

**Issue by clwm01** [Web-Feet/coastercms#46]
Hi, I met an error which outputs "Database error, settings table could not be found." when I run `php artisan list` command in terminal, I searched the database, the table "settings" is just there. So I ask for your help.

Here is some screenshots.

<img width="304" alt="xxyy2" src="https://user-images.githubusercontent.com/5001145/26924523-ce11c084-4c78-11e7-9a5a-faf398814d04.png">
<img width="426" alt="xxyy1" src="https://user-images.githubusercontent.com/5001145/26924524-ce434280-4c78-11e7-9d10-fed04a2debf9.png">

**Comment by clwm01** [comment]
I'm sure that the database connection is correct, I can read data via "System Settings" in backend.
<img width="1166" alt="xxyy4" src="https://user-images.githubusercontent.com/5001145/26924792-d35a0104-4c79-11e7-8866-0cf30cf25d6d.png">

**Comment by neil-jennings** [comment]
Not sure why you can't connect from the cmd line if it fine through the web server, only thing I can think of is it's using different environment variables.

I would check with the `env` command and if you find any of the database variables, ie. DB_PREFIX for example have been set you can unset it with `unset DB_PREFIX` .

**Comment by clwm01** [comment]
@neil-jennings Oh, bro, it's my fault! 😂 Feel sorry about this. I ran that command in a wrong environment. I use homestead as my development environment, but I ran that command in my **Host Machine**, I should ran that command in the **Virtual Machine**(or Guest Machine?) instead!.

---

Look at this screenshot:
<img width="276" alt="xxyy5" src="https://user-images.githubusercontent.com/5001145/26957343-ee5ab39a-4cf6-11e7-980e-fabb2b78bd2c.png">

The database configuration is correct, but it's configured for the **Virtual Machine**, not for the **Host Machine**, for the **Host Machine**, the database configuration should be something like below:
<img width="362" alt="xxyy8" src="https://user-images.githubusercontent.com/5001145/26957451-bbd3a58e-4cf7-11e7-96d6-5a30a108c151.png">

The difference here is the `DB_HOST`.

Now, it's OK.

Run `php artisan list` in **Virtual Machine**:
<img width="560" alt="xxyy6" src="https://user-images.githubusercontent.com/5001145/26957497-0741c7e4-4cf8-11e7-8d9c-4221d534bdec.png">

Run `php artisan list` in **Host Machine**:
<img width="585" alt="xxyy7" src="https://user-images.githubusercontent.com/5001145/26957511-1a333630-4cf8-11e7-87c0-db5f1b3bb305.png">

Feel sorry again! 😅
