### ISSUE TITLE
Dragdrop submenu opening

### ISSUE THREAD

**Issue by takl95** [Web-Feet/coastercms#49]
If you open a submenu by hovering over it with the mouse while dragging another menu, it pops open, but the icon doesn't change, hence the functionality of the + - gets reversed

**Comment by chadanuk** [comment]
Note. File is here: https://github.com/Web-Feet/coasterframework/blob/master/resources/views/admin/pages/pages.blade.php

**Comment by neil-jennings** [comment]
Fix added to the framework.
