### ISSUE TITLE
Trying to get property of non object 5_2_19_0_update_theme_actions.php (line 43)

### ISSUE THREAD

**Issue by jva91** [Web-Feet/coastercms#50]
I'm getting an error on the following file:
5_2_19_0_update_theme_actions.php (line 43)

First time install coastercms and run the migrations. But there isn't an update action on a theme controller inserted.

Anyone who has this same issue and already fixed it?

Before i runned this migration script, I let composer update my project to be sure it is the latest version

**Comment by jva91** [comment]
i commented this code but i think this will causes other exceptions.

**Comment by neil-jennings** [comment]
The theme action should be created from these two files:
5_2_0_0_create_admin_controllers.php   (themes controller should be set with id 16)
5_2_0_0_create_admin_actions.php   (update action added for controller id 16)

I would check both these tables to see what's missing, possible one of these didn't run ?
By default there should be 18 rows in the controller table and 80 rows in the actions table.

**Comment by jva91** [comment]
I got 18 rows in the admin_controllers table and 79 rows in the admin_actions table

It is this line:
`$updateAction = DB::table('admin_actions')->select('id')->where('controller_id', '=', $themesController->id)->where('action', '=', 'update')->first();` 
that causes an error because there is no admin_actions row with controller_id of themes and action is update in my case. 

I dont know in which file this row must be inserted.

**Comment by neil-jennings** [comment]
What database are you using ?
All the actions get added from one big array, not sure why just one would not get added:

https://github.com/Web-Feet/coasterframework/blob/v5.4.14/database/migrations/5_2_0_0_create_admin_actions.php#L656

**Comment by jva91** [comment]
I think i kwow the problem.

In the create_admin_actions migration there is a fixed controller id. But in our database configuration the id's could only be odd when there is an auto increment field. So the suggestion to set the controller_id to 16 is not working for every set. In our case the id of the themes controller is 31.

It would be better to set the controller id  in the admin controller manually in the insert script. (file: 5_2_0_0_create_admin_controllers.php)

**Comment by jva91** [comment]
i made a change and commit it to coasterframework repo

**Comment by jva91** [comment]
Fixed when set fixed id's in 5_2_0_0_create_admin_controllers.php
