### ISSUE TITLE
Website barely readable - please increase font contrast.

### ISSUE THREAD

**Issue by gaganova** [Web-Feet/coastercms#53]
The idea of using a light grey font on a near-white background is a very bad one if you want your website to be read by people. That design anti-pattern _maybe_ was something special about ten years ago when used in a provocative context, but nowadays it is only copy-pasted by people that have no education in graphics design (or a very bad one). Good Designers have understood, that the web should be readable and not hurt your readers eyes. Please also read http://contrastrebellion.com/ to better understand this important issue. Thanks.

**Comment by tliesnham** [comment]
Thanks for pointing this out to us, that was an interesting read. We'll take a look into ways we can improve the accessibility of the site.
