### ISSUE TITLE
Error in Video.php

### ISSUE THREAD

**Issue by SarajevoNo1** [Web-Feet/coastercms#55]
You have issue (bug) in new theme 2017 in some templates, like internal, blog etc... When editing or adding new template, create content and add or update we get this message (picture in attachment).

![error video php](https://user-images.githubusercontent.com/28009477/28249334-24f0d75c-6a54-11e7-9cb9-cc68a23d77b2.jpg)

**Comment by neil-jennings** [comment]
Thanks for the report, fixed in v5.4.17

**Comment by SarajevoNo1** [comment]
Hi it seems the problem is here again I try to add new page on FRESH INSTALLED SCRIPT WITH THIS COMMAND: composer create-project web-feet/coastercms [your_project_name]

And again I get error with Video.php but now IT IS IN LINE 69 as you an see in attachment image...

Thanks 
![video 69 line](https://user-images.githubusercontent.com/28009477/28266259-288a6022-6af4-11e7-90cd-f2e940245ef7.jpg)
