### ISSUE TITLE
Little bug with admin/login or /admin - in new theme 2017 fresh installed script - admin wont open error 404...

### ISSUE THREAD

**Issue by SarajevoNo1** [Web-Feet/coastercms#56]
![lokom1](https://user-images.githubusercontent.com/28009477/28264194-293a89e8-6aea-11e7-8bed-c48b48391877.jpg)
![lokom2](https://user-images.githubusercontent.com/28009477/28264195-295f95c6-6aea-11e7-8c72-433a4f3e1a08.jpg)

Now the problem is with admin - login/admin...in new fresh installed script... 

NEW FRESH INSTALLED SCRIPT cannot open admin dashboard and admin/login or /admin...:

http://lokom.croatiago.com/admin

**Comment by neil-jennings** [comment]
Looks like a routing issue with your app routes.
Make sure a catchall route is not added in your routes file or set before the coaster routes are declared.

**Comment by SarajevoNo1** [comment]
This error (with login in admin) is resolved with the moving, commenting or removing the routes from web.php what Chardwik says that we need to add when implementing lang switcher, for everybody of "COASTER LOVERS" to know, we are at the 99% finish line with the lang switcher (everything is set only url to finish all), And it was with GOD help and Neil help !!! :))


________________________________
Šalje: Neil Jennings <notifications@github.com>
Poslano: 18. srpnja 2017. 14:25
Prima: Web-Feet/coastercms
Kopija: SarajevoNo1; Author
Predmet: Re: [Web-Feet/coastercms] Little bug with admin/login or /admin - in new theme 2017 fresh installed script - admin wont open error 404... (#56)


Looks like a routing issue with your app routes.
Make sure a catchall route is not added in your routes file or set before the coaster routes are declared.

**Comment by SarajevoNo1** [comment]
This Ticket Can Be Closed ! Thanks Neil !


________________________________
Šalje: Neil Jennings <notifications@github.com>
Poslano: 18. srpnja 2017. 14:25
Prima: Web-Feet/coastercms
Kopija: SarajevoNo1; Author
Predmet: Re: [Web-Feet/coastercms] Little bug with admin/login or /admin - in new theme 2017 fresh installed script - admin wont open error 404... (#56)


Looks like a routing issue with your app routes.
Make sure a catchall route is not added in your routes file or set before the coaster routes are declared.
