### ISSUE TITLE
New Error issue with - Video line 69 when adding and updating some templates like (internal and some other more templates file.. etc...)

### ISSUE THREAD

**Issue by SarajevoNo1** [Web-Feet/coastercms#57]
New Error issue with - Video line 69 when adding and updating some templates like (INTERNAL and some other more templates file.. etc...) - check all templates... PLEASE UPDATE THESE TO FIX THIS ISSUE....

Image in attachment !!
THANKS:)

![internal and etc -video 69 line](https://user-images.githubusercontent.com/28009477/28268057-08149d54-6afd-11e7-997d-ccc38903d1ee.jpg)

**Comment by neil-jennings** [comment]
Made some updates, should be fixed in the v5.4.19

**Comment by SarajevoNo1** [comment]
For VIDEO - OK EXTRA - SUPER!! Than this ticket can be closed. The video problem was only with some specific templates (when editing and updating that templates) , last time for VIDEO.PHP on line 5... was with blog templates and some other, this time is for internal template in Video.php line 69. I think that now is OK for everything template in your updated version. 5.4.19. I will check these days everything again. But I think that this ticket is resolved if you updated for all templates and can be closed. Thanks Neil :))


________________________________
Šalje: Neil Jennings <notifications@github.com>
Poslano: 18. srpnja 2017. 14:26
Prima: Web-Feet/coastercms
Kopija: SarajevoNo1; Author
Predmet: Re: [Web-Feet/coastercms] New Error issue with - Video line 69 when adding and updating some templates like (internal and some other more templates file.. etc...) (#57)


Made some updates, should be fixed in the v5.4.19
