### ISSUE TITLE
Fresh Install via Composer issues

### ISSUE THREAD

**Issue by 0E800** [Web-Feet/coastercms#58]
v.5417
Installation goes smoothly without errors, however when I login to the admin panel and go to manage themes, the theme preview images do not show. When open Frontend view, logo is not displayed.

Nginx: error:
`48 open() "/var/www/laravel/public/cache/coaster/tmp/themes/default/screenshot-252x142.jpg" failed (2: No such file or directory)`

When I look inside public/cache/ there are no other folders or files.

There is also no documentation for commands used to create the needed permissions for whatever folders require permissions. Like I said, the initial install screen shows "Yes" for all needed folder permissions.

My install workflow:

`sudo composer create-project web-feet/coastercms laravel`
`cd /var/www/laravel`
`sudo chgrp -R www-data storage bootstrap/cache public/uploads public/cache public/coaster public/themes resources .env`

`sudo chmod -R ug+rwx storage bootstrap/cache public/uploads public/cache public/coaster public/themes resources .env`

Open browser to to mysite
![Imgur](http://i.imgur.com/WgFbQ7M.png)

Configure DB settings.
![Imgur](http://i.imgur.com/IiaAc4a.png)

Create Admin account:
![Imgur](http://i.imgur.com/1342vTB.png)

Install Theme:
![Imgur](http://i.imgur.com/Lz8tEOl.png)

Installation Complete:
![Imgur](http://i.imgur.com/qUiFBZS.png)

Admin Dashboard looks great:
![Imgur](http://i.imgur.com/T5vhDSe.png)

However, when I click on "Themes" -> "Manage Themes"
The image preview for the themes do no show. 
Browser console error:
X `GET http://34.213.8.82/cache/coaster/tmp/themes/default/screenshot-252x142.jpg`

![Imgur](http://i.imgur.com/h8ltFTz.png)

When I check the `public/cache` folder, all it has is .git file. No other folders.

Here is view of Frontend, everything seems to work except for missing logo:
`GET http://34.213.8.82/cache/coaster/tmp/themes/default/screenshot-252x142.jpg [HTTP/1.1 404 Not Found 31ms]`
![Imgur](http://i.imgur.com/Fo9KMU7.png)

Here is output from Composer installation:
https://pastebin.com/RwZ9eUgA

**Comment by chadanuk** [comment]
@0E800 The only thing I can think of is that the public/cache folder isn't writeable? (and it's not checked in the install - which maybe we should add)
