### ISSUE TITLE
Any <script> in the head section is being moved to the body

### ISSUE THREAD

**Issue by Dannymx** [Web-Feet/coastercms#61]
If we add any <script> code within the <head> section it will be removed to the body, I'm not sure what's the purpose of this, but there are instances where Javascript is needed in the head section.

Also, if moving the title below of any of those scripts, it will break the site with a DOM Exception.

**Comment by neil-jennings** [comment]
There was a bug trying to get round issues with DOMDocument and the script tag.
This should be fixed in the latest version.
