### ISSUE TITLE
Issue with blueimp file uploader and PHP 7.1?

### ISSUE THREAD

**Issue by Dannymx** [Web-Feet/coastercms#62]
This might not be a Coaster issue, but since I cannot open issues in their repo page, I'll report here to see if somebody has found a solution.

When uploading image files to a gallery, I get the following error: 
```
(1/1) ErrorException
A non well formed numeric value encountered
in UploadHandler.php (line 356)
/vendor/blueimp/jquery-file-upload/server/php/UploadHandler.php
```
This seems to be caused when the `post_max_size` value which is '100M' (for PHP 7.1 on homestead) is multiplied to an integer (1024).

Any ideas?

**Comment by chadanuk** [comment]
Looks like a bug in the upload handler? - @neil-jennings I think we need to update the file manager (https://github.com/Web-Feet/coasterframework/blob/master/src/Console/Assets/FileManager.php) now at 9.19.1 looks like they deal with this in their code now?

**Comment by neil-jennings** [comment]
I've updated the version of blueimp package used, hopefully this will fix your issue when you run a composer update.
