### ISSUE TITLE
php artisan coaster:update-assets failed to work on forge

### ISSUE THREAD

**Issue by beerbuddha** [Web-Feet/coastercms#63]
I am trying to deploy the CMS on a prod server by forge.

I am getting an error that on 'php artisan coaster:update-assets' that it doesnt exists.
All the other instructions I have done and it works on my local - however for this it doesnt.

Any idea?
also i tried to use your read me and you have a mistake from your own command:
echo "This script is deprecated, you should now run: php artisan coaster:update-assets \n";

**Comment by neil-jennings** [comment]
It could be some environment variables maybe ?
Also have you tried clearing the application cache before running the cmd ?
php aritsan cache:clear

The updateAssets.php file no longer can be called directly, will change the message soon.

**Comment by beerbuddha** [comment]
Hi Neil
which environment variable could that be?
app_env is set to default which is prod

**Comment by neil-jennings** [comment]
Not sure, was only thinking if forge had specific ones that might change something.
Haven't got much experience with using forge, though will runs some tests when I have the time.

**Comment by beerbuddha** [comment]
Hi @neil-jennings 
you are the first project that failed to deployed on forge but worked on local.
I have ran composer off the server to take care of dependencies. sO i am wondering what would the application do to not recognize it.

The only thing that comes to mind right now is for me to copy/paste your console commands upbound to the root /src level instead of of leaving it in vendor.

Maybe its a flaw in the latest 5.4.x of laravel framework?

Note: i created coaster-cms by using "create-project"

**Comment by beerbuddha** [comment]
as per @chadanuk suggestion `php artisan config:clear` before `php artisan coaster:update-assets` managed to solve the problem with deployment.
