### ISSUE TITLE
While Submitting Contact Form, Email Was Not Send

### ISSUE THREAD

**Issue by aslammakrani** [Web-Feet/coastercms#74]
While Submitting Contact Form, Email Not Send, Can Any One Plz Help Me How Can Admin Get Email When Contact Form Submited, With Contact Form Detail.

**Comment by chadanuk** [comment]
@aslammakrani 

A good way to check this is to use mailtrap (https://mailtrap.io/). 

Once you're signed up put the username and password into the '.env' file and emails should come into mailtrap.

This will prove if Coaster is sending the email

After that, it is likely a server set up problem.

If you want to bypass any server set up stuff then try 

https://www.mailgun.com/
