### ISSUE TITLE
Adding a link/document page without parent it show proper in menu but it gone into backend all pages view

### ISSUE THREAD

**Issue by aslammakrani** [Web-Feet/coastercms#75]
![error](https://user-images.githubusercontent.com/28642854/42463008-8989cf4c-83c2-11e8-9a4d-02f1fd1e91f6.png)

Adding a link/document page without parent it show proper in menu but it gone into backend all pages view, now how can i remove it?

**Comment by chadanuk** [comment]
@aslammakrani  Check the database pages table and you'll be able to see what happened to the page

**Comment by aslammakrani** [comment]
sorry but there is no table name like pages, check below list of my tables.

adrenth_redirect_categories
adrenth_redirect_clients
adrenth_redirect_redirects
adrenth_redirect_redirect_logs
backend_access_log
backend_users
backend_users_groups
backend_user_groups
backend_user_preferences
backend_user_roles
backend_user_throttle
cache
cms_theme_data
cms_theme_logs
deferred_bindings
failed_jobs
janvince_smallcontactform_messages
jobs
migrations
rainlab_sitemap_definitions
sessions
system_event_logs
system_files
system_mail_layoutsHide
system_mail_partials
system_mail_templates
system_parameters
system_plugin_history
system_plugin_versions
system_request_logs
system_revisions
system_settings

**Comment by chadanuk** [comment]
@aslammakrani That doesn't look like a coaster database? Have you run the migrations? 

`php artisan migrate --path=vendor/coasterframework/database/migrations/`

**Comment by aslammakrani** [comment]
yes i did, it say Nothing to migrate, and also i checked migration  table there is no table name like pages, there is all table which i add in above comment. and every thing is working fine excepting this issue.

**Comment by chadanuk** [comment]
How have you installed coaster? Is it on an existing Laravel application or using `composer create-project`?

**Comment by aslammakrani** [comment]
no first i download install-master dir and then run that dir index.php file and i follow there step and it installed.

**Comment by aslammakrani** [comment]
great you are right, thank you so much, when i install using your guide whole database was change.  thanks.
