### ISSUE TITLE
Error - Add new page.

### ISSUE THREAD

**Issue by m3chas** [Web-Feet/coastercms#8]
@chadanuk 

When I tried to add a new page I got this error:

QueryException in Connection.php line 761:
SQLSTATE[HY000]: General error: 1364 Field 'canonical_parent' doesn't have a default value (SQL: insert into `pages` (`template`, `parent`, `child_template`, `order`, `group_container`, `link`, `live`, `sitemap`, `live_start`, `live_end`, `group_container_url_priority`, `updated_at`, `created_at`) values (8, 0, 0, 6, 0, 0, 1, 1, , , 0, 2016-10-01 21:55:12, 2016-10-01 21:55:12))

**Comment by neil-jennings** [comment]
Hi Joaz,

Not sure why this has happened, the canonical_parent should have a default value of 0 from the [migrations](https://github.com/Web-Feet/coasterframework/blob/master/database/migrations/5_3_0_0_update_group_pages.php). An alter table query should fix it though.
`ALTER TABLE pages MODIFY COLUMN canonical_parent int(11) NOT NULL;`

Also you could try updating to the latest version of coaster and going to the url /admin/system/validate-db . This script should double check the migrations have run properly.

Regards,
Neil

**Comment by m3chas** [comment]
Thank you for the reply.

This happened after I run /admin/system/validate-db.
