### ISSUE TITLE
How to display recent blogs by post_date or by id ?

### ISSUE THREAD

**Issue by vmore5** [Web-Feet/coastercms#83]
Hello ,
I was trying to display recent blogs with the help of post Date.
I have also added post date category in group settings with order dir as "descending".
But it didnt work .

Please give some suggestion to implement it !

Thanks

![Screenshot from 2019-05-27 18-10-28](https://user-images.githubusercontent.com/51084754/58421094-b8858880-80ac-11e9-8607-330ae99f1d91.png)

**Comment by chadanuk** [comment]
@vmore5 Does removing the image field from the group attributes have any effect?

**Comment by vmore5** [comment]
@chadanuk Thank you for replying.
Resolved that issue. I set its priority to 10 , previously it was 0. 
Now it is working !
