### ISSUE TITLE
Error 'Table 'users' already exists' during install of CoasterCms on an existing Laravel (v8) project

### ISSUE THREAD

**Issue by cvlug** [Web-Feet/coastercms#88]
https://github.com/CoasterCms/coastercms says CoasterCms can be installed on an existing Laravel (v8) project.
When i do that, i get error 'Table 'users' already exists' during install of CoasterCms.
This is not suprisingly, because CoasterCms tries to make table users again. While on an existing Laravel, table users is allready made.
What is suprisingly, is that CoasterCms says is can be installed on an existing Laravel project, but tries to install the excisting tables again.
Is it really possible to install CoasterCms  on an existing Laravel project?
What needs to be done to accomplish that?
Ofcourse,  i could modify the CoaserCms migrations, and check id tables exist( \Schema::hasTable('users');) and than add custom migrations, to add the extra colums that CoasterCms  needs. But will other problems arise after that?

**Comment by tliesnham** [comment]
Is your existing project using a 'users' table already?

**Comment by cvlug** [comment]
Yes. Laravel comes with a users table.

**Comment by neil-jennings** [comment]
There will be a users table conflict if you've already run the default Laravel migrations. 

The table however is very similar to the one Coaster tries to create. You may just be able to remove/rename your table, run the Coaster install and then make any changes you need to on top of the Coaster users table.

**Comment by cvlug** [comment]
Thanks.

I now have all the tables in place.

 

It seems Coaster is not working nice together with Laravel Spark.

I get this error on some random frontend page: Call to undefined method CoasterCms\Models\User::onGenericTrial()

I think Coaster let Laravel use its own user class, and that user class misses the Spark functions, like onGenericTrial()

 

Ofcourse, I could place these missing function in de Coaster user class, but I am wandering where the need of modifications will be finished. Perhaps I have to change a lot of code.

 

Van: Neil Jennings <notifications@github.com> 
Verzonden: woensdag 3 maart 2021 18:17
Aan: CoasterCms/coastercms <coastercms@noreply.github.com>
CC: cvlug <cvlug@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [CoasterCms/coastercms] Error 'Table 'users' already exists' during install of CoasterCms on an existing Laravel (v8) project (#88)

 

There will be a users table conflict if you've already run the default Laravel migrations.

The table however is very similar to the one Coaster tries to create. You may just be able to remove/rename your table, run the Coaster install and then make any changes you need to on top of the Coaster users table.

**Comment by neil-jennings** [comment]
Coaster does override the default web auth config which may be causing the issue.

You could try to force Coaster to use a modified user class (or even user prodvider as well), by putting this in your service provider.
```php
resolve(AuthManager::class)->provider('coaster-provider', function ($app, $config) {
    return new CoasterUserProvider($app['hash'], YourExtendedUser::class);
});
```

It is possible to disable Coaster overwriting the auth config, but going down this route might be a bit more work.

https://github.com/CoasterCms/framework/blob/8.x/config/coaster.php#L88
`php artisan vendor:publish --tag coaster.config` to publish to your config folder & edit.
