### ISSUE TITLE
ErrorException in SystemController.php line 310

### ISSUE THREAD

**Issue by cpass78** [Web-Feet/coastercms#9]
On a new install on ubuntu 14.04 php5.6.23 clicking on the system settings link from the admin throws up an exception error: **Invalid operand type was used: expecting an array**

This works fine locally on homestead PHP 7.0.8-2+deb.sury.org~xenial+1.

**Comment by tliesnham** [comment]
Hi cpass,

Sorry for the delayed response, unfortunately we are all based in the UK.

It would seem as though there is some sort of compatibility issue with PHP 5.6. I'm going to setup a testing environment and see if I can recreate the error.

Kind regards,
Taylor

**Comment by cpass78** [comment]
No worries and thanks. I spun up a new server with PHP 7.0.11-2+deb.sury.org~xenial+2 and everything is working again.

**Comment by tliesnham** [comment]
It's great to hear you've got it working. If you need any help with getting started with theme development, feel free to post on the [forum](https://www.coastercms.org/forum/). 

We've since added a fix for PHP 5.6 support in the development branch, which we will merge shortly.
